config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|vi/ do
    root to: "static_pages#home"
    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    resources :users
    resources :account_activations, only: %i(edit)
    resources :password_resets, only: %i(new create edit update)
    resources :microposts, only: %i(create destroy)
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, :valid_user, :check_expiration, only: %i(edit update)
  attr_reader :user

  def new; end

  def create
    @user = User.find_by email: params[:password_reset][:email].downcase

    danger unless user
    send_mail user
  end

  def edit; end

  def update
    if params[:user][:password].empty?
      user.errors.add :password, t("password.error")
      render :edit
    elsif user.update_attributes user_params
      reset_pass user
    else
      render :edit
    end
  end

  private

  def danger
    render :new
    flash.now[:danger] = t "flash.danger.email_notfound"
  end

  def user_params
    params.require(:user).permit :password, :password_confirmation
  end

  def get_user
    @user = User.find_by email: params[:email]

    return if user
    flash[:error] = t "layouts.application.error"
    redirect_to rool_url
  end

  def valid_user
    return if user && user.activated? && user.authenticated?(:reset, params[:id])
    redirect_to root_url
  end

  def check_expiration
    return unless user.password_reset_expired?
    flash[:danger] = t "password.danger"
    redirect_to new_password_reset_url
  end

  def send_mail user
    user.create_reset_digest
    user.send_password_reset_email
    flash[:info] = t "password.info"
    redirect_to root_url
  end

  def reset_pass user
    log_in user
    user.update_attributes reset_digest: nil
    flash[:success] = t "password.success"
    redirect_to user
  end
end

app/views/password_resets/edit.html.erb
<% provide :title, t("password.reset") %>
<h1><%= t "password.reset" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: password_reset_path(params[:id]) do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, t("password.confirm") %>

      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit t("password.update_pass"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide :title, t("password.forgot") %>
<h1><%= t "password.forgot" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :password_reset, url: password_resets_path do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.submit t("action.submit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>